name: Build Backend

on:
  push:
    branches: [ master ]
    paths:
    - 'src/Organizer.API/**'
  workflow_dispatch:
    
jobs:
  Build-Backend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x
    - name: Build .NET Backend
      run: dotnet publish Organizer.API.csproj -o "output" -c "Release"
      working-directory: ./src/Organizer.API/Organizer.API

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: organizer-backend
        path: ./src/Organizer.API/Organizer.API/output/*
        if-no-files-found: error
        retention-days: 90
