name: Build Frontend

on:
  push:
    branches: [ master ]
    paths:
    - 'src/Organizer.SPA/**'

  workflow_dispatch:

jobs:
  Build-Frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Angular Build
        run: |
          npm install
          npm run build -- --base-href ./ --output-path=dist --configuration='production'
        working-directory: ./src/Organizer.SPA/

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: organizer-frontend
          path: ./src/Organizer.SPA/dist/*
          if-no-files-found: error
          retention-days: 90
